export interface Passenger {
    age:any;
    birthDate:string;
    countryIataCode:string;
    createdDatePerson:string;
    createdDateUser:string;
    email:string;
    firstName:string;
    frequentFlyer:string;
    gender:string;
    isVIP:boolean;
    lastName:string;
    lcostCenter:any;
    loginUser:string;
    lpersonDocuments:any;
    message:any;
    nationality:string;
    orole:any;
    personId:string;
    phone:string;
    travelerCode:string;
    userId:string;
}