export const environment = {
/*   production: true,
  url: "https://domiruth-prd.azure-api.net/security/",
  url_2: "https://domiruth-prd.azure-api.net/flight/",
  url_5: 'https://domiruth-prd.azure-api.net/customer/',
  url_6: 'https://domiruth-prd.azure-api.net/notify/',
  url_hotel: "https://domiruth-prd.azure-api.net/hotel/",
  urlIp: 'https://api.ipify.org/?format=json',
  urlVisa: 'https://domiruth-prd.azure-api.net/visa/',
  url_insurance: 'https://domiruth-prd.azure-api.net/insurance/',
  urlVisaSource: 'https://static-content.vnforapps.com/v2/js/checkout.js',
  url_reports : "http://reports-api.domiruth.com/api/",
  url_project : "https://localhost:4200",
  url_policy: "https://domiruth-prd.azure-api.net/policy/",
  cod_rol_autogestion: [1],
  cod_rol_autorizador: [2],
  cod_rol_centralizador: [3], 
  url_cars: "https://domiruth-prd.azure-api.net/cars/",
  baseUrl: 'https://domiruth-prd.azure-api.net/vacation/',
  max_pax: 8,
  url_bnus: 'https://ws-bnu.domiruth.com/api/',
  key: '78e06a82cb2e4ddfb445f10d4ac6b36e',
 url_reportGeneral: 'https://domiruth-prd.azure-api.net/report/',
 url_customer: 'https://domiruth-prd.azure-api.net/customer/' */

 production: false,
 url: "https://uat-api.goarrival.com/security/v1/",
 url_2: "https://uat-api.goarrival.com/flight/v1/",
 url_5: 'https://uat-api.goarrival.com/customer/v1/',
 url_6: 'https://uat-api.goarrival.com/notification/v1/',
 url_reports : "http://reports-api.domiruth.com/api/",
 url_hotel: "https://uat-api.goarrival.com/hotel/v1/",
 url_insurance: 'https://uat-api.goarrival.com/insurance/v1/',
 url_policy: "https://uat-api.goarrival.com/policy/v1/",
 baseUrl: 'https://uat-api.goarrival.com/vacation/v1/', 
 urlIp: 'https://api.ipify.org/?format=json',
 urlVisa: 'https://uat-api.goarrival.com/visa/v1/',
urlVisaSource: 'https://static-content-qas.vnforapps.com/v2/js/checkout.js?qa=true',
 url_project : "http://sigvplus.azurewebsites.net",
 cod_rol_autogestion: [1],
 cod_rol_autorizador: [2],
 cod_rol_centralizador: [3],
 max_pax: 8,
 url_bnus: 'https://ws-bnu.domiruth.com/api/',
 key: "eb85131bc9d94c02840aa6961e7f77e9",
 url_reportGeneral: 'https://uat-api.goarrival.com/report/v1/',
 url_customer: 'https://uat-api.goarrival.com/customer/v1/',
 url_cars: "https://uat-api.goarrival.com/cars/v1/"
};
